import { applyCoverage, defaultCoverageAnswers } from '../../model/insuranceCoverage'
import { childrenEngineFields, type ChildrenAnswer } from '../../model/childrenAnswer'
import { InsuranceRateAssumptions } from '../InputPanel/InsuranceRateAssumptions'
// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { useState } from 'react'
import { fireEvent, render, screen, within } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { RetirementInsuranceSection } from '../InputPanel/RetirementInsuranceSection'
import { RetirementIncomeStreamsSection } from '../InputPanel/RetirementIncomeStreamsSection'
import { InsuranceBreakdown } from '../InsuranceBreakdown'
import { clearHiddenInvalidInsuranceValues, createDefaultRetirementInsurance, insuranceSetupIssues, type RetirementInsurance } from '../../model/retirementInsurance'
import { insuredInput, pension, automaticInsurance, completedCoverage } from '../../model/__tests__/insuranceFixtures'
import { simulateScenario } from '../../model/simulateScenario'
import { rentenlueckeInputSchema } from '../../model/inputSchema'
import type { RetirementIncomeStream } from '../../model/types'

function Harness({ initial = pension({ support: undefined }), config = createDefaultRetirementInsurance(67), workStop = 67 }: {
  initial?: RetirementIncomeStream; config?: RetirementInsurance; workStop?: number
}) {
  const [coverage, setCoverage] = useState(() => config.pension.circumstances === 'standard' ? completedCoverage() : defaultCoverageAnswers())
  const [rawInsurance, setInsurance] = useState(config)
  const [childrenAnswer, setChildrenAnswer] = useState<ChildrenAnswer>(config.isParent === undefined ? { kind: 'missing' } : config.isParent ? { kind: 'children', rows: [{ id: 'older', year: 1980 }] } : { kind: 'none' })
  const [streams, setStreams] = useState([initial])
  const input = clearHiddenInvalidInsuranceValues(insuredInput({ currentAge: workStop, retirementAge: workStop, planningAge: 70, retirementIncomeStreams: streams, retirementInsurance: { ...applyCoverage(rawInsurance, coverage), ...childrenEngineFields(childrenAnswer) } }))
  const insurance = input.retirementInsurance!
  const issues = insuranceSetupIssues(input)
  const valid = rentenlueckeInputSchema.safeParse(input).success && !issues.length
  return <>
    <RetirementInsuranceSection coverage={coverage} onCoverageChange={setCoverage} insurance={insurance} input={input} onChange={setInsurance} childrenAnswer={childrenAnswer} onChildrenChange={setChildrenAnswer} />
    <details><summary>Rechenannahmen</summary><InsuranceRateAssumptions insurance={insurance} onChange={setInsurance} /></details>
    <RetirementIncomeStreamsSection input={input} streams={streams} insurance={insurance}
      onUpdate={(id, patch) => setStreams(current => current.map(stream => stream.id === id ? { ...stream, ...patch } : stream))}
      onAdd={() => {}} onRemove={id => setStreams(current => current.filter(stream => stream.id !== id))} />
    {issues.length > 0 && <p role="status">{issues.join(' ')}</p>}
    {valid && <InsuranceBreakdown rows={simulateScenario(input).retirementRows} streams={streams} />}
  </>
}
function change(label: string | RegExp, value: string) { const field = screen.queryByLabelText(label) ?? screen.getByLabelText(typeof label === 'string' ? label.replace('Rentenphase', 'Phase ab Versicherungsübergang') : label); fireEvent.change(field, { target: { value } }) }
const breakdown = () => screen.queryByRole('heading', { name: 'Monatliche KV/PV-Aufschlüsselung' })
function confirmKvdr() {
  change('Versicherungsstatus – Rentenphase', 'kvdr')
  fireEvent.click(within(screen.getByRole('group', { name: 'Besondere Umstände – Rentenphase' })).getByLabelText('Alle Standardregeln genügen (automatische Berechnung)'))
  change('Art bestätigen – Pension', 'standard')
  change('Kassenindividueller Zusatzbeitrag (%)', '2.9')
  fireEvent.click(screen.getByRole('button', { name: 'Keine anerkannten Kinder' }))
}

describe('guided insurance fields and ledger breakdown', () => {
  it('starts unanswered, requires confirmation, and removes the forecast when an answer is cleared', () => {
    render(<Harness />)
    expect(breakdown()).not.toBeInTheDocument()
    expect(screen.getByLabelText('Versicherungsstatus – Rentenphase')).toHaveValue('')
    expect(screen.queryByText(/Schätzung aktivieren/)).not.toBeInTheDocument()
    confirmKvdr()
    expect(breakdown()).toBeInTheDocument()
    change('Kassenindividueller Zusatzbeitrag (%)', '')
    expect(breakdown()).not.toBeInTheDocument()
    expect(screen.getAllByRole('status').some(node => node.textContent?.includes('Zusatzbeitrag angeben'))).toBe(true)
    change('Kassenindividueller Zusatzbeitrag (%)', '0')
    expect(breakdown()).toBeInTheDocument()
    change('Kassenindividueller Zusatzbeitrag (%)', '-1')
    expect(screen.getByLabelText('Kassenindividueller Zusatzbeitrag (%)')).toHaveAttribute('aria-invalid', 'true')
    expect(breakdown()).not.toBeInTheDocument()
  })
  it('requires unknown-status capital and subsidy answers, allows explicit zero, hides them under KVdR', () => {
    render(<Harness />)
    confirmKvdr()
    change('Versicherungsstatus – Rentenphase', 'unknown')
    expect(screen.getByText(/Für diese Planung nehmen wir freiwillige GKV an/)).toBeVisible()
    expect(breakdown()).not.toBeInTheDocument()
    change('Kapitalbasis – Rentenphase', 'manual')
    change('Beitragsrelevante Kapitalerträge – Rentenphase (€/Monat heute)', '0')
    expect(breakdown()).not.toBeInTheDocument()
    change('Rentenversicherungszuschuss einplanen?', 'not-received')
    expect(breakdown()).toBeInTheDocument()
    change('Versicherungsstatus – Rentenphase', 'kvdr')
    expect(screen.queryByLabelText(/Beitragsrelevante Kapitalerträge/)).not.toBeInTheDocument()
    expect(screen.queryByLabelText('Rentenversicherungszuschuss einplanen?')).not.toBeInTheDocument()
  })
  it('keeps a saved manual phase in manual mode when its estimate is cleared', () => {
    render(<Harness initial={pension()} config={automaticInsurance({ pension: { status: 'voluntary', circumstances: 'standard', capitalMonthlyToday: 100, drvSubsidy: 'not-received' } })} />)
    change('Beitragsrelevante Kapitalerträge – Rentenphase (€/Monat heute)', '')
    expect(screen.getByLabelText('Kapitalbasis – Rentenphase')).toHaveValue('manual')
    expect(screen.getByLabelText('Beitragsrelevante Kapitalerträge – Rentenphase (€/Monat heute)')).toHaveValue(null)
    expect(breakdown()).not.toBeInTheDocument()
  })
  it('answers through birth years and returns to missing when the final row is removed', () => {
    render(<Harness config={automaticInsurance({ isParent: undefined })} initial={pension()} />)
    fireEvent.click(screen.getByRole('button', { name: 'Anerkanntes Kind hinzufügen' }))
    expect(screen.getByLabelText('Geburtsjahr Kind 1')).toHaveValue(null)
    expect(breakdown()).not.toBeInTheDocument()
    change('Geburtsjahr Kind 1', '2002')
    expect(breakdown()).toBeInTheDocument()
    change('Geburtsjahr Kind 1', '')
    expect(breakdown()).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Kind 1 entfernen' }))
    expect(breakdown()).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Keine anerkannten Kinder' }))
    expect(breakdown()).toBeInTheDocument()
  })
  it('requires only manual totals for unsupported phases and allows returning to automatic coverage', () => {
    render(<Harness initial={pension({ kind: 'private-rente' })} />)
    expect(screen.queryByLabelText('Kassenindividueller Zusatzbeitrag (%)')).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/Kapitalerträge/)).not.toBeInTheDocument()
    change('Eigene KV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '200')
    change('Eigene PV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '50')
    expect(breakdown()).toBeInTheDocument()
    expect(screen.getByText(/Gesamte Phase manuell nach allen Zuschüssen/)).toBeVisible()
    expect(screen.getByText('1.750 €')).toBeVisible()
    change('Kategorie von Pension', 'gesetzliche-rente')
    expect(breakdown()).not.toBeInTheDocument()
    expect(screen.getByLabelText('Kassenindividueller Zusatzbeitrag (%)')).toBeVisible()
    confirmKvdr()
    expect(breakdown()).toBeInTheDocument()
  })
  it.each(['gesetzliche-rente', 'betriebsrente'] as const)('clears special classification when changing %s to rental and requires fresh pension confirmation', kind => {
    render(<Harness initial={pension({ kind })} config={automaticInsurance()} />)
    change('Art bestätigen – Pension', 'unsupported')
    expect(breakdown()).not.toBeInTheDocument()
    expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen/)).toBeVisible()
    change('Kategorie von Pension', 'rental-income')
    expect(screen.queryByLabelText('Art bestätigen – Pension')).not.toBeInTheDocument()
    expect(screen.queryByLabelText(/Eigene KV nach allen Zuschüssen/)).not.toBeInTheDocument()
    expect(breakdown()).toBeInTheDocument()
    change('Versicherungsstatus – Rentenphase', 'voluntary')
    expect(screen.getByLabelText(/Beitragsrelevanter Mietüberschuss/)).toBeVisible()
    change(/Beitragsrelevanter Mietüberschuss/, '1500')
    change('Kapitalbasis – Rentenphase', 'manual')
    change('Beitragsrelevante Kapitalerträge – Rentenphase (€/Monat heute)', '0')
    change('Rentenversicherungszuschuss einplanen?', 'not-received')
    expect(breakdown()).toBeInTheDocument()
    change('Kategorie von Pension', kind)
    expect(screen.getByLabelText('Art bestätigen – Pension')).toHaveValue('')
    expect(breakdown()).not.toBeInTheDocument()
    change('Art bestätigen – Pension', 'standard')
    expect(breakdown()).toBeInTheDocument()
  })
  it('preserves valid rate overrides when an invalid rate is hidden by manual mode and returns to automatic', () => {
    render(<Harness initial={pension()} config={automaticInsurance()} />)
    fireEvent.click(screen.getByText('Rechenannahmen'))
    change(/Allgemeiner KV-Satz/, '16')
    change(/PV-Basissatz/, '4')
    change(/Ermäßigter KV-Satz/, '-1')
    expect(breakdown()).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText(/Eigene KV\/PV-Beiträge einsetzen – (Rentenphase|Phase ab Versicherungsübergang)/))
    expect(screen.getByLabelText(/Allgemeiner KV-Satz/)).toHaveValue(16)
    change('Eigene KV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '100')
    change('Eigene PV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '20')
    expect(breakdown()).toBeInTheDocument()
    fireEvent.click(within(screen.getByRole('group', { name: 'Besondere Umstände – Rentenphase' })).getByLabelText('Alle Standardregeln genügen (automatische Berechnung)'))
    expect(breakdown()).toBeInTheDocument()
    fireEvent.click(screen.getByText('Rechenannahmen'))
    expect(screen.getByLabelText(/Allgemeiner KV-Satz/)).toHaveValue(16)
    expect(screen.getByLabelText(/PV-Basissatz/)).toHaveValue(4)
    expect(screen.getByLabelText(/Ermäßigter KV-Satz/)).toHaveValue(null)
    const section = screen.getByRole('region', { name: 'Monatliche KV/PV-Aufschlüsselung' })
    expect(within(section).getAllByText('189 €').length).toBeGreaterThan(0)
    expect(within(section).getAllByText('80 €').length).toBeGreaterThan(0)
  })
  it('offers phase navigation with independent bridge totals and shows negative available income', () => {
    render(<Harness initial={pension()} config={automaticInsurance()} workStop={65} />)
    expect(screen.getByLabelText('Berechnungsjahr auswählen')).toHaveValue('67')
    fireEvent.click(screen.getByRole('button', { name: 'Erstes Brückenjahr' }))
    expect(screen.getByLabelText('Berechnungsjahr auswählen')).toHaveValue('65')
    expect(screen.getByText(/Die Beiträge übersteigen das Einkommen/)).toBeVisible()
    change('Versicherungsstatus – Brücke', 'unsupported')
    expect(screen.queryByLabelText('Versicherungsumstände – Brücke')).not.toBeInTheDocument()
    expect(screen.queryByLabelText('Beitragsrelevante Kapitalerträge – Brücke (€/Monat heute)')).not.toBeInTheDocument()
    change('Eigene KV nach allen Zuschüssen – Brücke (€/Monat heute)', '100')
    change('Eigene PV nach allen Zuschüssen – Brücke (€/Monat heute)', '0')
    expect(breakdown()).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Erstes Rentenjahr' }))
    expect(screen.getByLabelText('Berechnungsjahr auswählen')).toHaveValue('67')
  })
  it('shows rental assessment only when needed and keeps excluded net income usable', () => {
    render(<Harness initial={pension({ id: 'rent', kind: 'rental-income', amountBasis: 'net' })} config={automaticInsurance()} />)
    expect(breakdown()).toBeInTheDocument()
    expect(screen.queryByLabelText(/Beitragsrelevanter Mietüberschuss/)).not.toBeInTheDocument()
    change('Versicherungsstatus – Rentenphase', 'voluntary')
    expect(screen.getByLabelText(/Beitragsrelevanter Mietüberschuss/)).toBeVisible()
    change('Betragsart von Pension', 'gross')
    change(/Beitragsrelevanter Mietüberschuss/, '1500')
    change('Kapitalbasis – Rentenphase', 'manual')
    change('Beitragsrelevante Kapitalerträge – Rentenphase (€/Monat heute)', '0')
    change('Rentenversicherungszuschuss einplanen?', 'not-received')
    expect(breakdown()).toBeInTheDocument()
    fireEvent.click(screen.getByLabelText(/Eigene KV\/PV-Beiträge einsetzen – (Rentenphase|Phase ab Versicherungsübergang)/))
    expect(screen.queryByLabelText(/Beitragsrelevanter Mietüberschuss/)).not.toBeInTheDocument()
  })
  it('displays the selected ledger funding shortfall including insurance', () => {
    const input = insuredInput({ currentCapital: 100, monthlyDesiredSpendingToday: 100000 })
    const result = simulateScenario(input)
    render(<InsuranceBreakdown rows={result.retirementRows} streams={input.retirementIncomeStreams!} />)
    expect(screen.getByRole('alert')).toHaveTextContent(/Vermögenslücke:.*einschließlich KV\/PV/)
  })
  it('displays separate assessment and subsidy values directly from the selected ledger row', () => {
    const input = insuredInput()
    const rows = simulateScenario(input).retirementRows
    render(<InsuranceBreakdown rows={rows} streams={input.retirementIncomeStreams!} />)
    const section = screen.getByRole('region', { name: 'Monatliche KV/PV-Aufschlüsselung' })
    expect(within(section).getByText('2.000 € / 2.000 €')).toBeVisible()
    expect(within(section).getByText('1.681 €')).toBeVisible()
    fireEvent.click(screen.getByText('Bemessung und Grenzen erklären'))
    expect(screen.getByText(/ein gemeinsamer Betriebsrenten-KV-Freibetrag/)).toBeVisible()
  })
})

it('shows vertical applicable ranges, restricts bridge status, and renders shared controls once', () => {
  render(<Harness initial={pension()} workStop={65} />)
  expect(screen.getByRole('group', { name: 'Brücke · Alter 65 bis unter 67' })).toBeVisible()
  expect(screen.getByRole('group', { name: 'Rentenphase · Alter 67 bis unter 70' })).toBeVisible()
  expect(within(screen.getByLabelText('Versicherungsstatus – Brücke')).queryByRole('option', { name: /KVdR/ })).toBeNull()
  expect(screen.getAllByLabelText('Kassenindividueller Zusatzbeitrag (%)')).toHaveLength(1)
  expect(screen.getAllByRole('button', { name: 'Keine anerkannten Kinder' })).toHaveLength(1)
  fireEvent.click(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Brücke'))
  fireEvent.click(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase'))
  expect(screen.queryByLabelText('Kassenindividueller Zusatzbeitrag (%)')).toBeNull()
  expect(screen.queryByRole('button', { name: 'Keine anerkannten Kinder' })).toBeNull()
})

it('copies in both directions without asserting bridge-only coverage and keeps multiple exceptions visible', () => {
  render(<Harness initial={pension()} workStop={65} />)
  const group = (phase: string) => within(screen.getByRole('group', { name: `Besondere Umstände – ${phase}` }))
  fireEvent.click(group('Rentenphase').getByLabelText('Alle Standardregeln genügen (automatische Berechnung)'))
  fireEvent.click(screen.getByRole('button', { name: 'Angaben aus der anderen Phase übernehmen – Brücke' }))
  expect(group('Brücke').getByLabelText('Alle Standardregeln genügen (automatische Berechnung)')).toBeChecked()
  expect(within(screen.getByRole('group', { name: 'Zusätzlich in der Brücke' })).getByLabelText('Alle Standardregeln genügen (automatische Berechnung)')).not.toBeChecked()
  expect(screen.getByText(/Brücken-spezifische Angaben bleiben/)).toBeVisible()
  fireEvent.click(group('Brücke').getByLabelText('Es trifft etwas zu'))
  fireEvent.click(group('Brücke').getByLabelText('Krankengeld'))
  fireEvent.click(group('Brücke').getByLabelText('Mehrere Personen'))
  expect(group('Brücke').getByLabelText('Krankengeld')).toBeChecked()
  expect(group('Brücke').getByLabelText('Mehrere Personen')).toBeChecked()
  expect(group('Brücke').getByLabelText('Alle Standardregeln genügen (automatische Berechnung)')).not.toBeChecked()
  fireEvent.click(screen.getByRole('button', { name: 'Angaben aus der anderen Phase übernehmen – Rentenphase' }))
  expect(group('Rentenphase').getByLabelText('Krankengeld')).toBeChecked()
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen – Rentenphase/)).toBeVisible()
  fireEvent.click(group('Rentenphase').getByLabelText('Ich bin unsicher'))
  fireEvent.click(group('Rentenphase').getByLabelText('Es trifft etwas zu'))
  expect(group('Rentenphase').getByLabelText('Es trifft etwas zu')).toBeChecked()
  expect(group('Rentenphase').getByLabelText('Krankengeld')).not.toBeChecked()
  expect(group('Rentenphase').getByText('Noch offen: Mindestens eine Ausnahme ankreuzen, oder die Antwort oben ändern.')).toBeVisible()
  expect(screen.queryByLabelText(/Eigene KV nach allen Zuschüssen – Rentenphase/)).not.toBeInTheDocument()
  fireEvent.click(group('Rentenphase').getByLabelText('Krankengeld'))
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen – Rentenphase/)).toBeVisible()
})

it('retains valid inactive manual totals, capital and subsidy but clears the active override on return', () => {
  render(<Harness initial={pension()} config={automaticInsurance({ pension: { status: 'unknown', circumstances: 'standard', capitalMode: 'manual', capitalMonthlyToday: 123, drvSubsidy: 'confirmed' } })} />)
  const summary = screen.getByTestId('insurance-pension-summary')
  expect(summary).toHaveTextContent('Unbekannt · freiwillige GKV angenommen · automatisch')
  expect(summary).not.toHaveTextContent('€')
  fireEvent.click(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase'))
  expect(screen.queryByLabelText('Rentenversicherungszuschuss einplanen?')).toBeNull()
  change('Eigene KV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '0')
  change('Eigene PV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '25')
  expect(summary).toHaveTextContent('KV 0 / PV 25 €/Monat heute')
  fireEvent.click(within(screen.getByRole('group', { name: 'Besondere Umstände – Rentenphase' })).getByLabelText('Alle Standardregeln genügen (automatische Berechnung)'))
  expect(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase')).not.toBeChecked()
  expect(screen.getByLabelText('Rentenversicherungszuschuss einplanen?')).toHaveValue('confirmed')
  expect(screen.getByLabelText(/Beitragsrelevante Kapitalerträge/)).toHaveValue(123)
  expect(breakdown()).toBeInTheDocument()
  fireEvent.click(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase'))
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen/)).toHaveValue(0)
  expect(screen.getByLabelText(/Eigene PV nach allen Zuschüssen/)).toHaveValue(25)
})

it('defers phase cards on an unusable timeline and labels a nonstatutory transition', () => {
  const view = render(<Harness config={createDefaultRetirementInsurance(NaN)} />)
  expect(screen.queryByLabelText(/Versicherungsstatus/)).toBeNull()
  expect(screen.getByRole('button', { name: 'Zeitplan ergänzen / korrigieren' })).toBeVisible()
  view.unmount()
  render(<Harness initial={pension({ kind: 'rental-income' })} />)
  expect(screen.getByRole('group', { name: 'Phase ab Versicherungsübergang · Alter 67 bis unter 70' })).toBeVisible()
  expect(within(screen.getByRole('group', { name: 'Kranken- und Pflegeversicherung' })).queryByText(/Rentenphase/)).toBeNull()
})

it('coverage unsure requires both own totals, including explicit zero; returning to none restores automatic calculation', () => {
  render(<Harness initial={pension()} config={automaticInsurance()} />)
  const common = within(screen.getByRole('group', { name: 'Besondere Umstände – Rentenphase' }))
  fireEvent.click(common.getByLabelText('Ich bin unsicher'))
  expect(breakdown()).not.toBeInTheDocument()
  expect(screen.queryByLabelText('Kassenindividueller Zusatzbeitrag (%)')).not.toBeInTheDocument()
  expect(screen.getByTestId('insurance-pension-summary')).toHaveTextContent('KV offen / PV offen €/Monat heute')
  change('Eigene KV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '0')
  expect(breakdown()).not.toBeInTheDocument()
  change('Eigene PV nach allen Zuschüssen – Rentenphase (€/Monat heute)', '0')
  expect(breakdown()).toBeInTheDocument()
  expect(screen.getByTestId('insurance-pension-summary')).toHaveTextContent('KV 0 / PV 0 €/Monat heute')
  fireEvent.click(common.getByLabelText('Alle Standardregeln genügen (automatische Berechnung)'))
  expect(screen.getByTestId('insurance-pension-summary')).toHaveTextContent('KVdR · automatisch')
  expect(screen.queryByLabelText(/Eigene KV nach allen Zuschüssen/)).not.toBeInTheDocument()
  expect(breakdown()).toBeInTheDocument()
})

it.each(['voluntary', 'unknown'] as const)('places %s estimates after shared facts and requires a subsidy planning choice', status => {
  render(<Harness initial={pension()} workStop={65} config={automaticInsurance({ pension: { status, circumstances: 'standard', capitalMode: 'manual', capitalMonthlyToday: 0 } })} />)
  const card = screen.getByRole('group', { name: 'Rentenphase · Alter 67 bis unter 70' })
  expect(within(card).queryByLabelText('Rentenversicherungszuschuss einplanen?')).toBeNull()
  expect(within(card).queryByLabelText(/Kapitalbasis/)).toBeNull()
  const shared = screen.getByRole('region', { name: /2\. Gemeinsame Angaben/ })
  const estimate = screen.getByRole('group', { name: 'Automatische Beiträge – Rentenphase' })
  expect(card.compareDocumentPosition(shared) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  expect(shared.compareDocumentPosition(estimate) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()
  const subsidy = screen.getByLabelText('Rentenversicherungszuschuss einplanen?')
  expect(subsidy).toHaveValue('')
  expect(within(subsidy).getByRole('option', { name: 'Ja' })).toHaveValue('confirmed')
  expect(within(subsidy).getByRole('option', { name: 'Nein, nicht ansetzen' })).toHaveValue('not-received')
  expect(breakdown()).not.toBeInTheDocument()
  change('Rentenversicherungszuschuss einplanen?', 'confirmed')
  expect(breakdown()).toBeInTheDocument()
  change('Rentenversicherungszuschuss einplanen?', 'not-received')
  expect(breakdown()).toBeInTheDocument()
  expect(within(screen.getByRole('group', { name: 'Brücke · Alter 65 bis unter 67' })).queryByLabelText(/Zuschuss/)).toBeNull()
})

it('shows exactly the existing checklist exclusions, the own-contribution radio, and the prefilled insurer rate', () => {
  render(<Harness workStop={65} />)
  const common = within(screen.getByRole('group', { name: 'Besondere Umstände – Brücke' }))
  expect(common.getAllByRole('radio').map(control => control.parentElement?.textContent)).toEqual([
    'Alle Standardregeln genügen (automatische Berechnung)', 'Es trifft etwas zu', 'Ich bin unsicher',
    'Eigene KV/PV-Beiträge einsetzen – Brücke',
  ])
  fireEvent.click(common.getByLabelText('Es trifft etwas zu'))
  expect(common.getAllByRole('checkbox').map(control => control.parentElement?.textContent)).toEqual([
    'Mehrere Personen', 'Beschäftigung oder Selbstständigkeit', 'Krankengeld', 'Partner- oder Haushaltsbemessung', 'Besondere Mindestbeitragsregeln', 'Anerkennung von Kindern ungeklärt',
  ])
  fireEvent.click(within(screen.getByRole('group', { name: 'Zusätzlich in der Brücke' })).getByLabelText('Es trifft etwas zu'))
  expect(within(screen.getByRole('group', { name: 'Zusätzlich in der Brücke' })).getAllByRole('checkbox').map(control => control.parentElement?.textContent)).toEqual(['Rentenantragstellerregelung', 'Familienversicherung', 'Sozialleistungsregelung'])
  expect(Number((screen.getByLabelText('Kassenindividueller Zusatzbeitrag (%)') as HTMLInputElement).value)).toBeCloseTo(2.9, 5)
  fireEvent.click(screen.getByText('Wo finde ich das?'))
  expect(screen.getByText(/Website oder in einer Beitragsmitteilung/)).toBeVisible()
})

it('keeps an exceptions-mode answer unanswered until one exception is checked, then requires manual totals', () => {
  render(<Harness workStop={65} />)
  const bridge = within(screen.getByRole('group', { name: 'Besondere Umstände – Brücke' }))
  expect(bridge.queryByLabelText('Krankengeld')).not.toBeInTheDocument()
  fireEvent.click(bridge.getByLabelText('Es trifft etwas zu'))
  expect(bridge.getByLabelText('Krankengeld')).toBeInTheDocument()
  expect(bridge.getByText('Noch offen: Mindestens eine Ausnahme ankreuzen, oder die Antwort oben ändern.')).toBeVisible()
  expect(breakdown()).not.toBeInTheDocument()
  expect(screen.queryByLabelText(/Eigene KV nach allen Zuschüssen – Brücke/)).not.toBeInTheDocument()
  fireEvent.click(bridge.getByLabelText('Krankengeld'))
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen – Brücke/)).toBeVisible()
  expect(screen.getByLabelText(/Eigene PV nach allen Zuschüssen – Brücke/)).toBeVisible()
})

it('unsupported status preselects own contributions, disables automatic radios, and focuses the own-contribution action', () => {
  render(<Harness />)
  change('Versicherungsstatus – Rentenphase', 'unsupported')
  const forced = within(screen.getByRole('group', { name: 'Besondere Umstände – Rentenphase' }))
  expect(forced.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase')).toBeChecked()
  expect(forced.getByLabelText('Alle Standardregeln genügen (automatische Berechnung)')).toBeDisabled()
  expect(forced.getByLabelText('Es trifft etwas zu')).toBeDisabled()
  expect(forced.getByLabelText('Ich bin unsicher')).toBeDisabled()
  expect(forced.getByText(/Diese Phase benötigt eigene Beiträge wegen:/)).toBeVisible()
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen/)).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Eigene Beiträge eingeben' }))
  expect(document.activeElement).toBe(screen.getByLabelText(/Eigene KV nach allen Zuschüssen/))
  // The forced status constraint keeps own contributions selected; clicking the preselected radio is a no-op.
  fireEvent.click(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase'))
  expect(screen.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Rentenphase')).toBeChecked()
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen/)).toBeVisible()
  expect(breakdown()).not.toBeInTheDocument()
})

it.each(['-1', '20.01'])('rejects additional contribution %s and preserves explicit zero interpretation', invalid => {
  render(<Harness initial={pension()} config={automaticInsurance()} />)
  change('Kassenindividueller Zusatzbeitrag (%)', invalid)
  expect(screen.getByLabelText('Kassenindividueller Zusatzbeitrag (%)')).toHaveAttribute('aria-invalid', 'true')
  expect(breakdown()).not.toBeInTheDocument()
  change('Kassenindividueller Zusatzbeitrag (%)', '0')
  expect(screen.getByLabelText('Kassenindividueller Zusatzbeitrag (%)')).toHaveValue(0)
  expect(breakdown()).toBeInTheDocument()
})

it('stays on "Es trifft etwas zu" after "Ich bin unsicher" and requires one exception for manual totals', () => {
  render(<Harness workStop={65} />)
  const bridge = within(screen.getByRole('group', { name: 'Besondere Umstände – Brücke' }))
  fireEvent.click(bridge.getByLabelText('Ich bin unsicher'))
  expect(bridge.getByLabelText('Ich bin unsicher')).toBeChecked()
  fireEvent.click(bridge.getByLabelText('Es trifft etwas zu'))
  expect(bridge.getByLabelText('Es trifft etwas zu')).toBeChecked()
  expect(bridge.getByLabelText('Krankengeld')).toBeInTheDocument()
  expect(bridge.getByText('Noch offen: Mindestens eine Ausnahme ankreuzen, oder die Antwort oben ändern.')).toBeVisible()
  expect(bridge.getByText('Noch offen: Bitte ausdrücklich antworten.')).toBeVisible()
  expect(screen.queryByLabelText(/Eigene KV nach allen Zuschüssen – Brücke/)).not.toBeInTheDocument()
  fireEvent.click(bridge.getByLabelText('Krankengeld'))
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen – Brücke/)).toBeVisible()
  expect(screen.getByLabelText(/Eigene PV nach allen Zuschüssen – Brücke/)).toBeVisible()
})

it('preselects own contributions with disabled automatic radios for a forced Sonderfall phase', () => {
  render(<Harness initial={pension({ kind: 'private-rente' })} />)
  const group = within(screen.getByRole('group', { name: 'Besondere Umstände – Phase ab Versicherungsübergang' }))
  expect(group.getByLabelText('Eigene KV/PV-Beiträge einsetzen – Phase ab Versicherungsübergang')).toBeChecked()
  expect(group.getByLabelText('Alle Standardregeln genügen (automatische Berechnung)')).toBeDisabled()
  expect(group.getByLabelText('Es trifft etwas zu')).toBeDisabled()
  expect(group.getByLabelText('Ich bin unsicher')).toBeDisabled()
  expect(group.getByText(/Diese Phase benötigt eigene Beiträge wegen:/)).toBeVisible()
  expect(group.getByText(/Einkommensart nicht automatisch geklärt/)).toBeVisible()
  expect(screen.getByLabelText(/Eigene KV nach allen Zuschüssen/)).toBeVisible()
  expect(breakdown()).not.toBeInTheDocument()
})
